name: Release

on:
  push:
    tags:
      - release.*

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "flutter/devtools"
          ref: "v2.16.0"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.0-0.0.pre"
          channel: "master"
      - run: sudo apt-get update -y && sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - name: Build
        working-directory: ./packages/devtools_app
        run: "flutter create --platforms=linux . && flutter build linux --release"
      - run: tar -cvzf linux-release.tar.gz -C ./packages/devtools_app/build/linux/x64/release/bundle .
      - run: cd ./packages/devtools_app/build/linux/x64/release/bundle && zip -r ../../../../../../../linux-release.zip .
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-release-targz
          path: ./linux-release.tar.gz
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-release-zip
          path: ./linux-release.zip

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "flutter/devtools"
          ref: "v2.16.0"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.0-0.0.pre"
          channel: "master"
      - name: Build
        working-directory: ./packages/devtools_app
        run: "flutter build web --release"
      - run: tar -cvzf web-release.tar.gz -C ./packages/devtools_app/build/web .
      - run: cd ./packages/devtools_app/build/web && zip -r ../../../../web-release.zip .
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-release-targz
          path: ./web-release.tar.gz
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-release-zip
          path: ./web-release.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "flutter/devtools"
          ref: "v2.16.0"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.0-0.0.pre"
          channel: "master"
      - run: flutter config --enable-windows-desktop
      - name: Build
        working-directory: ./packages/devtools_app
        run: "flutter create --platforms=windows . && flutter build windows"
      - run: tar.exe -a -c -C ./packages/devtools_app/build/windows/runner/Release -f windows-release.zip .
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-release
          path: ./windows-release.zip
  
  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-web, build-windows]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: linux-release-targz
      - uses: actions/download-artifact@master
        with:
          name: linux-release-zip
      - uses: actions/download-artifact@master
        with:
          name: web-release-targz
      - uses: actions/download-artifact@master
        with:
          name: web-release-zip
      - uses: actions/download-artifact@master
        with:
          name: windows-release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            ./linux-release.zip
            ./linux-release.tar.gz
            ./web-release.zip
            ./web-release.tar.gz
            ./windows-release.zip
