name: Release

on:
  push:
    tags:
      - release.*
  repository_dispatch:
    types: [release]

jobs:
  build:
    strategy:
      matrix:
        config:
        - runs_on: ubuntu-latest
          name: linux-release
          pre_run: sudo apt-get update -y && sudo apt-get install -y ninja-build libgtk-3-dev
          build: flutter config --enable-linux-desktop && flutter create --platforms=linux . && flutter build linux --release --no-tree-shake-icons
          output: /linux/x64/release/bundle
        - runs_on: ubuntu-latest
          name: web-release
          pre_run: ""
          build: flutter create --platforms=web . && flutter build web --release --no-tree-shake-icons
          output: /web
        - runs_on: windows-latest
          name: windows-release
          pre_run: ""
          build: flutter config --enable-windows-desktop && flutter create --platforms=windows . && flutter build windows --no-tree-shake-icons
          output: /windows/x64/runner/Release
    runs-on: ${{ matrix.config.runs_on }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: self

      - name: Get Latest Version
        id: getLatestVersion
        run: |
          latest=$(cat self/latest.txt)
          echo "latest=$latest" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          repository: "flutter/devtools"
          ref: ${{ steps.getLatestVersion.outputs.latest }}
          path: devtools
      - uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: ${{ matrix.config.pre_run }}
      - name: Build
        working-directory: ./devtools/packages/devtools_app
        run: ${{ matrix.config.build }}
      - name: Archive Release
        uses: thedoctor0/zip-release@0.6.2
        with:
          type: zip
          filename: ${{ github.workspace }}/${{ matrix.config.name }}.zip
          directory: ./devtools/packages/devtools_app/build${{ matrix.config.output }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.name }}
          path: ./${{ matrix.config.name }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-release
      - uses: actions/download-artifact@v4
        with:
          name: web-release
      - uses: actions/download-artifact@v4
        with:
          name: windows-release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{github.event.client_payload.ref}} 
          files: |
            ./linux-release.zip
            ./web-release.zip
            ./windows-release.zip
